# Generated by Django 6.1.1 on 2026-09-21 08:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_tag"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="catalog_tag_name_ci_unique",
                violation_error_message="A tag with this name already exists.",
            ),
        ),
    ]
