# Generated by Django 6.1.1 on 2026-09-21 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                max_length=2000,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
    ]
