# Generated by Django 6.1.1 on 2026-09-21 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "id"]},
        ),
    ]
